spring.application.name=backend

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/water_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Real Email Service Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mayankdwivedi24@gmail.com
spring.mail.password=xjqeoqiqqkyuunfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT Security Secret Key
jwt.secret=waterMonitoringSuperSecretKeyForJWTAuth2026WithEnoughLength
jwt.expiration=36000000